# Generated by Django 2.1 on 2019-03-16 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0002_auto_20190316_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='movie_role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MovieLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imdb.Languages')),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='movie',
            name='crew',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='director',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='lead_actors',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='writers',
        ),
        migrations.AddField(
            model_name='movielanguage',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imdb.Movie'),
        ),
        migrations.AddField(
            model_name='movie_role',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imdb.Movie'),
        ),
        migrations.AddField(
            model_name='movie_role',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imdb.Person'),
        ),
        migrations.AddField(
            model_name='movie_role',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imdb.Roles'),
        ),
    ]
