# Generated by Django 2.1 on 2019-03-16 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0003_auto_20190316_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_role',
            name='role',
            field=models.IntegerField(choices=[(0, 'NR - Not Rated'), (1, 'G - General Audiences'), (2, 'PG - Parental Guidance Suggested'), (3, 'R - Restricted')], default=3),
        ),
        migrations.DeleteModel(
            name='Roles',
        ),
    ]
