# Generated by Django 2.1 on 2019-03-16 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0004_auto_20190316_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_role',
            name='role',
            field=models.IntegerField(choices=[(0, 'Lead_actor'), (1, 'Director'), (2, 'Writer'), (3, 'CREW')], default=3),
        ),
    ]
