# Generated by Django 2.1 on 2019-03-16 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0005_auto_20190316_1845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='languages',
            old_name='lang',
            new_name='language',
        ),
    ]
