# Generated by Django 2.1 on 2019-03-17 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0006_auto_20190316_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
