# Generated by Django 2.1 on 2019-03-17 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0007_auto_20190317_0533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.FloatField(),
        ),
    ]
